use strict;
use warnings;

use Bio::Root::Test;
use Bio::Seq;

test_begin(-tests => 12);
my $debug = test_debug();

use_ok('Bio::PrimerDesigner');
require_ok('Bio::PrimerDesigner');

can_ok('Bio::PrimerDesigner', "new");
ok(my $pd = Bio::PrimerDesigner->new(-verbose => $debug));

isa_ok($pd, 'Bio::PrimerDesigner');

can_ok($pd, 'register_pre_process');
can_ok($pd, 'registered_pre_processes');
can_ok($pd, 'register_post_process');
can_ok($pd, 'registered_post_processes');
can_ok($pd, 'design');



# ok, start with just running Primer3Redux with default settings and no hooks
my $seq1 = 'GTGCATAGATTACAGGTCTGTGTCACCACACCAGTCCTTGTTTTGTGAGACAAGGGTTTGTTTCAGTAGTAGCCTGGCCCTGCTGAATTCTTGCTTCTTGAGGCTATTATTAACAAGTCTAGGAAGATAGGTGTGAGCCACAAAACCCTGGCCAGCCTAGCACTCCCTCTCCTGCCTCAGCCTTCTGATGTCTAAGACAAGCAGATGCAGATACTGAGATGGGTGTACTTAGCTTTATTGAACTTTTAGTGTTTGGTTGAATGTTTGATAGTACTGGGCATAGAGTAACTTCAACATTTATCGGAGTTGATTCATTCTGTCAGATACAATCAGAATGGATTGTAACTGTCAACCCTAGAATGGCACTTTGCATATGTATATATGTACAAAAGGGTGGAAGAGTGCTTAGGGCAATTTCAGAAATGGTTGGAAATTCTGCTCTGGTCTCAAAGTGAAACTTTGTTAAATGCTTTGTTTTGTTTTTTAAACTCAAGTTTGTGGCTGTGCATGGTGATGCATAGCTTGAATCCCAGTGACTTCCAGGACAGCCAGGGCTGGACAAATAGAACCCTCTCTGGGGTAGGGTGGACTGGAGGATAGGGTTGGGGGTGACAGGCACAAAACAAGAAAAATTCAGGTCTGCTGTTCTAAAGGGCAAACATTCTAATCCGGTCTGCACACAGTAGGGAAGGATAGAAGGCTTTAGATTCTGAAGTGGGGACCGTTATGTTTCCATAAGACCAGAAACTTCATGTGTGCAGTGAAAATTGCAGTTGCTAACAGCAGTGGTCTGCAGTGTGAGCCAGGGCTCCTAGCTGCTGCATGCACAGACCCCAGTGTTCTGTGCATGGAGAACCAGGGCTACAGGTAGGGCTGCCAGAAACAGCTCAGATTTTATTTTATTATTATGATGTAGTCAGGCTGTCCTGGATTCACAGAAATCCACCTGTCTCCATCTCCCAGTGCTGGGATCAAAGGCTTGTGCCACTACACCTGGCTTAGATTTTGAATTAATTTTA';
my $seq2 = 'AGCGTCCTGTGCTGGAATGTGCGGCTCCCGCGAGCTCGCGGCGCAGCAGCAGAAGACCGAGGAGCGCCGCCGAGGCCGCGGGCCCCAGACCCGGGCGGCCGGGACCGCAGCGACGGCAGAACCAGGGCCGGCGGTCTGATCCCGCTCCGCGATCGCACCCCGGGATCTCGAGGGCCTCGAGGGGCGGGATCGAGTTACGGAGCGAGTCACGGGCTGGGCCGGGGGCTGGTGCGGAGCGGCGTGGGCATCGGCCCCCAGCGGAGCACGGGGAGGCCCTTCCGCACGGCGCTGAGATCCGGG';


$seq1 = Bio::Seq->new( -seq => $seq1,
		       -id  => 'seq_1'
		     );


$seq2 = Bio::Seq->new( -seq => $seq2,
		       -id  => 'seq_2'
		     );

ok(my @res = $pd->design($seq1, $seq2));
isa_ok($res[0], 'Bio::Tools::Primer3Redux::Result');

#my $r1 = $res->next_result;
#isa_ok($r1, 'Bio::Tools::Primer3Redux::Result');


#ok, now try realistic Primer3 settings.
#$pd->primer3->set_parameters(
#			     PRIMER_MISPRIMING_LIBRARY => 'repbase/humrep.ref',
#			     PRIMER_OPT_GC_PERCENT     => 60,
#			     PRIMER_MIN_GC             => 40,
#			     PRIMER_MAX_GC             => 80,
#			     PRIMER_PRODUCT_OPT_SIZE   => 120,
#			     PRIMER_PRODUCT_SIZE_RANGE => "100-150",
#			     PRIMER_OPT_SIZE           => 20,
#			     PRIMER_MIN_SIZE           => 18,
#			     PRIMER_MAX_MISPRIMING     => 12,
#			     PRIMER_MIN_TM             => 57,
#			     PRIMER_SELF_ANY           => 4,
#			     PRIMER_GC_CLAMP           => 2,
#			     PRIMER_NUM_NS_ACCEPTED    => 0,
#			     PRIMER_OPT_TM             => 60,
#			     PRIMER_MAX_POLY_X         => 5,
#			     PRIMER_SALT_CONC          => 50,
#			     PRIMER_MAX_TM             => 63,
#			     PRIMER_SELF_END           => 3,
#			     PRIMER_MAX_DIFF_TM        => 100,
#			     PRIMER_MAX_SIZE           => 27,
#			     PRIMER_NUM_RETURN         => 5
#);
#
#
#is($pd->primer3->PRIMER_NUM_RETURN, 5);
